services:
  datahub-gms:
    environment:
    - MAE_CONSUMER_ENABLED=false
    - MCE_CONSUMER_ENABLED=false
  datahub-mae-consumer:
    container_name: datahub-mae-consumer
    depends_on:
    - neo4j
    environment:
    - DATAHUB_GMS_HOST=datahub-gms
    - DATAHUB_GMS_PORT=8080
    - MAE_CONSUMER_ENABLED=true
    - PE_CONSUMER_ENABLED=true
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - KAFKA_SCHEMAREGISTRY_URL=http://datahub-gms:8080/schema-registry/api/
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200
    - ES_BULK_REFRESH_POLICY=WAIT_UNTIL
    - NEO4J_HOST=http://neo4j:7474
    - NEO4J_URI=bolt://neo4j
    - NEO4J_USERNAME=neo4j
    - NEO4J_PASSWORD=datahub
    - GRAPH_SERVICE_IMPL=neo4j
    - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-mae-consumer/resources/entity-registry.yml
    hostname: datahub-mae-consumer
    image: ${DATAHUB_MAE_CONSUMER_IMAGE:-linkedin/datahub-mae-consumer}:${DATAHUB_VERSION:-head}
    ports:
    - 9091:9091
  datahub-mce-consumer:
    container_name: datahub-mce-consumer
    depends_on:
    - neo4j
    environment:
    - DATAHUB_SERVER_TYPE=${DATAHUB_SERVER_TYPE:-quickstart}
    - DATAHUB_TELEMETRY_ENABLED=${DATAHUB_TELEMETRY_ENABLED:-true}
    - NEO4J_HOST=http://neo4j:7474
    - NEO4J_URI=bolt://neo4j
    - NEO4J_USERNAME=neo4j
    - NEO4J_PASSWORD=datahub
    - GRAPH_SERVICE_IMPL=neo4j
    - MCE_CONSUMER_ENABLED=true
    - EBEAN_DATASOURCE_USERNAME=datahub
    - EBEAN_DATASOURCE_PASSWORD=datahub
    - EBEAN_DATASOURCE_HOST=mysql:3306
    - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
    - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - KAFKA_SCHEMAREGISTRY_URL=http://datahub-gms:8080/schema-registry/api/
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200
    - ES_BULK_REFRESH_POLICY=WAIT_UNTIL
    - GRAPH_SERVICE_DIFF_MODE_ENABLED=true
    - JAVA_OPTS=-Xms1g -Xmx1g
    - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-mce-consumer/resources/entity-registry.yml
    - DATAHUB_SYSTEM_CLIENT_ID=__datahub_system
    - DATAHUB_SYSTEM_CLIENT_SECRET=JohnSnowKnowsNothing
    - ENTITY_SERVICE_ENABLE_RETENTION=true
    - MAE_CONSUMER_ENABLED=false
    - PE_CONSUMER_ENABLED=false
    - UI_INGESTION_ENABLED=false
    hostname: datahub-mce-consumer
    image: ${DATAHUB_MCE_CONSUMER_IMAGE:-linkedin/datahub-mce-consumer}:${DATAHUB_VERSION:-head}
    ports:
    - 9090:9090
version: '2.3'
