# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

ingestion:
  - changed-files:
      - any-glob-to-any-file:
          - "metadata-ingestion/**/*"
          - "metadata-ingestion-modules/**/*"
          - "metadata-integration/**/*"

devops:
  - changed-files:
      - any-glob-to-any-file:
          - "docker/**/*"
          - ".github/**/*"
          - "perf-test/**/*"
          - "metadata-service/**/*"

product:
  - changed-files:
      - any-glob-to-any-file:
          - "datahub-web-react/**/*"
          - "datahub-frontend/**/*"
          - "datahub-graphql-core/**/*"
          - "metadata-io/**/*"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"

smoke_test:
  - changed-files:
      - any-glob-to-any-file:
          - "smoke-test/**/*"
