ingestion:
- changed-files:
  - any-glob-to-any-file:
    - "metadata-ingestion/**/*"
    - "metadata-ingestion-modules/**/*"
    - "metadata-integration/**/*"

devops:
- changed-files:
  - any-glob-to-any-file:
    - "docker/**/*"
    - ".github/**/*"
    - "perf-test/**/*"
    - "metadata-service/**/*"

product:
- changed-files:
  - any-glob-to-any-file:
    - "datahub-web-react/**/*"
    - "datahub-frontend/**/*"
    - "datahub-graphql-core/**/*"
    - "metadata-io/**/*"

docs:
- changed-files:
  - any-glob-to-any-file:
    - "docs/**/*"

smoke_test:
- changed-files:
  - any-glob-to-any-file:
    - "smoke-test/**/*"
