dist: trusty

sudo: required

language: java

jdk:
  - oraclejdk8

env:
  - DOCKER_COMPOSE_VERSION=1.14.0

services:
  - docker
  - elasticsearch

before_install:
  # elasticsearch
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.3/elasticsearch-2.3.3.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.3.deb && sudo service elasticsearch restart

  # extralibs
  - wget https://github.com/ericsun2/sandbox/raw/master/extralibs/extralibs.zip
  - mkdir -p wherehows-etl/extralibs; unzip extralibs.zip -d wherehows-etl/extralibs

  # docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
- ./gradlew check assemble
- ./gradlew jacocoFullReport coveralls && ./gradlew emberCoverage
- (cd wherehows-docker && ./build.sh latest)
- (cd wherehows-docker && docker-compose config)

after_script:
  - rm -rf $WHEREHOWS_DIR/coverage
