language: java

jdk:
  - oraclejdk8

before_install:
  # download play 2.2.4
  - wget http://downloads.typesafe.com/play/2.2.4/play-2.2.4.zip
  - unzip play-2.2.4.zip && rm play-2.2.4.zip && mv play-2.2.4 $HOME/
  - export PLAY_HOME="$HOME/play-2.2.4"
  - echo $PLAY_HOME

  # change the build file stack size
  - sed -i -e 's/-Xss1M/-Xss2M/g' $PLAY_HOME/framework/build
  - cat $PLAY_HOME/framework/build

  # elasticsearch
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.3/elasticsearch-2.3.3.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.3.deb && sudo service elasticsearch restart

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - mysql
  - elasticsearch

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
  - mysql -u root -e 'create database if not exists wherehows'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost'"
  - cd data-model/DDL; mysql -u root -D wherehows < create_all_tables_wrapper.sql; cd ../..
  - wget https://github.com/ericsun2/sandbox/raw/master/extralibs/extralibs.zip
  - mkdir -p metadata-etl/extralibs; unzip extralibs.zip -d metadata-etl/extralibs
  - sleep 5

