language: java

jdk:
  - oraclejdk8

before_install:
  # elasticsearch
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.3/elasticsearch-2.3.3.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.3.deb && sudo service elasticsearch restart

  # extralibs
  - wget https://github.com/ericsun2/sandbox/raw/master/extralibs/extralibs.zip
  - mkdir -p metadata-etl/extralibs; unzip extralibs.zip -d metadata-etl/extralibs
  - mkdir -p restli-client/extralibs; unzip extralibs.zip -d restli-client/extralibs

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - mysql
  - elasticsearch

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
  - mysql -u root -e 'create database if not exists wherehows'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost'"
  - cd data-model/DDL; mysql -u root -D wherehows < create_all_tables_wrapper.sql; cd ../..
  - sleep 5

after_success:
- ./gradlew jacocoFullReport coveralls
