[tools]
actionlint = "1.7.11"
java = "17"
node = "22"
python = "3.11"
shellcheck = "0.11.0"
yarn = "4.12.0"

[tasks.regenerate-pre-commit]
description = "Regenerate the pre-commit configuration to add new/removed projects"
run = "python3 .github/scripts/generate_pre_commit.py"
