{{- if .Values.exporters.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datahub-gms.fullname" . }}-config-jmx-exporter
  labels:
    {{- include "datahub-gms.labels" . | nindent 4 }}
data:
  config.yml: |-
    hostPort: localhost:{{ .Values.env.JMXPORT }}
    lowercaseOutputName: {{ .Values.exporters.jmx.config.lowercaseOutputName }}
    lowercaseOutputLabelNames: {{ .Values.exporters.jmx.config.lowercaseOutputLabelNames }}
    rules:
{{ .Values.exporters.jmx.config.rules | toYaml | indent 6 }}
    ssl: false
    startDelaySeconds: {{ .Values.exporters.jmx.config.startDelaySeconds }}
{{- end }}
