# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

services:
  datahub-mae-consumer:
    image: acryldata/datahub-mae-consumer:debug
    build:
      context: ../
      dockerfile: docker/datahub-mae-consumer/Dockerfile
      args:
        APP_ENV: dev
    volumes:
    - ./datahub-mae-consumer/start.sh:/datahub/datahub-mae-consumer/scripts/start.sh
    - ../metadata-models/src/main/resources/:/datahub/datahub-mae-consumer/resources
    - ../metadata-jobs/mae-consumer-job/build/libs/:/datahub/datahub-mae-consumer/bin/
    - ./monitoring/client-prometheus-config.yaml:/datahub/datahub-mae-consumer/scripts/prometheus-config.yaml
  datahub-mce-consumer:
    image: acryldata/datahub-mce-consumer:debug
    build:
      context: ../
      dockerfile: docker/datahub-mce-consumer/Dockerfile
      args:
        APP_ENV: dev
    volumes:
    - ./datahub-mce-consumer/start.sh:/datahub/datahub-mce-consumer/scripts/start.sh
    - ../metadata-jobs/mce-consumer-job/build/libs/:/datahub/datahub-mce-consumer/bin
    - ./monitoring/client-prometheus-config.yaml:/datahub/datahub-mce-consumer/scripts/prometheus-config.yaml
