# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

---
services:
  datahub-mae-consumer:
    environment:
      - ENABLE_PROMETHEUS=true
      - ENABLE_OTEL=true
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one:14250
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=datahub-mae-consumer
    ports:
      - "4318"

  datahub-mce-consumer:
    environment:
      - ENABLE_PROMETHEUS=true
      - ENABLE_OTEL=true
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one:14250
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=datahub-mce-consumer
    ports:
      - "4318"
