---
version: '3.5'
services:
  datahub-gms:
    environment:
      - ENABLE_PROMETHEUS=true
      - ENABLE_OTEL=true
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one:14250
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=datahub-gms
    ports:
      - "4318"

  datahub-frontend-react:
    environment:
      - ENABLE_PROMETHEUS=true
      - ENABLE_OTEL=true
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one:14250
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=datahub-gms
    ports:
      - "4318"

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9089:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

volumes:
  grafana-storage: