# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

scrape_configs:
  - job_name: 'jmx'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'host.docker.internal:4318'
        - 'datahub-gms:4318'
        - 'datahub-mae-consumer:4318'
        - 'datahub-mce-consumer:4318'
        - 'datahub-frontend-react:4318'