
x-datahub-frontend-service: &datahub-frontend-service
  hostname: datahub-frontend-react
  image: ${DATAHUB_FRONTEND_IMAGE:-${DATAHUB_REPO:-acryldata}/datahub-frontend-react}:${DATAHUB_VERSION:-head}
  ports:
    - ${DATAHUB_MAPPED_FRONTEND_PORT:-9002}:9002
  env_file:
    - datahub-frontend/env/docker.env
    - ${DATAHUB_LOCAL_COMMON_ENV:-empty.env}
    - ${DATAHUB_LOCAL_FRONTEND_ENV:-empty2.env}
  environment: &datahub-frontend-service-env
    KAFKA_BOOTSTRAP_SERVER: broker:29092
    DATAHUB_GMS_HOST: ${DATAHUB_GMS_HOST:-datahub-gms}
  volumes:
    - ${HOME}/.datahub/plugins:/etc/datahub/plugins

x-datahub-frontend-service-dev: &datahub-frontend-service-dev
  <<: *datahub-frontend-service
  image: ${DATAHUB_FRONTEND_IMAGE:-${DATAHUB_REPO:-acryldata}/datahub-frontend-react}:${DATAHUB_VERSION:-debug}
  ports:
    - ${DATAHUB_MAPPED_FRONTEND_DEBUG_PORT:-5002}:5002
    - ${DATAHUB_MAPPED_FRONTEND_PORT:-9002}:9002
  environment:
    <<: *datahub-frontend-service-env
    JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5002
    DATAHUB_ANALYTICS_ENABLED: ${DATAHUB_ANALYTICS_ENABLED:-true}
  volumes:
    - ../../datahub-frontend/build/stage/main:/datahub-frontend
    - ./monitoring/client-prometheus-config.yaml:/datahub-frontend/client-prometheus-config.yaml

services:
  frontend-quickstart:
    <<: *datahub-frontend-service
    profiles:
      - quickstart
      - quickstart-frontend
    depends_on:
      system-update-quickstart:
        condition: service_completed_successfully
  frontend-quickstart-cassandra:
    <<: *datahub-frontend-service
    profiles:
      - quickstart-cassandra
    depends_on:
      system-update-quickstart-cassandra:
        condition: service_completed_successfully
  frontend-quickstart-postgres:
    <<: *datahub-frontend-service
    profiles:
      - quickstart-postgres
    depends_on:
      system-update-quickstart-postgres:
        condition: service_completed_successfully
  frontend-quickstart-consumers:
    <<: *datahub-frontend-service
    profiles:
      - quickstart-consumers
    depends_on:
      system-update-quickstart:
        condition: service_completed_successfully
  frontend-debug:
    <<: *datahub-frontend-service-dev
    profiles:
      - debug
    depends_on:
      system-update-debug:
        condition: service_completed_successfully
  frontend-debug-frontend:
    <<: *datahub-frontend-service-dev
    profiles:
      - debug-frontend
    depends_on:
      mysql-setup-dev:
        condition: service_completed_successfully
      opensearch-setup-dev:
        condition: service_completed_successfully
      kafka-setup-dev:
        condition: service_completed_successfully
  frontend-debug-postgres:
    <<: *datahub-frontend-service-dev
    profiles:
      - debug-postgres
    depends_on:
      system-update-debug-postgres:
        condition: service_completed_successfully
  frontend-debug-cassandra:
    <<: *datahub-frontend-service-dev
    profiles:
      - debug-cassandra
    depends_on:
      system-update-debug-cassandra:
        condition: service_completed_successfully
  frontend-debug-consumers:
    <<: *datahub-frontend-service-dev
    profiles:
      - debug-consumers
    depends_on:
      system-update-debug:
        condition: service_completed_successfully
  frontend-debug-neo4j:
    <<: *datahub-frontend-service-dev
    profiles:
      - debug-neo4j
    depends_on:
      system-update-debug-neo4j:
        condition: service_completed_successfully
  frontend-debug-elasticsearch:
    <<: *datahub-frontend-service-dev
    profiles:
      - debug-elasticsearch
    depends_on:
      system-update-debug-elasticsearch:
        condition: service_completed_successfully