
x-datahub-actions-service: &datahub-actions-service
  hostname: actions
  image: ${DATAHUB_ACTIONS_IMAGE:-${DATAHUB_ACTIONS_REPO:-acryldata}/datahub-actions}:${ACTIONS_VERSION:-v0.0.14}
  env_file: datahub-actions/env/docker.env
  environment:
    ACTIONS_EXTRA_PACKAGES: ${ACTIONS_EXTRA_PACKAGES:-}
    ACTIONS_CONFIG: ${ACTIONS_CONFIG:-}
    KAFKA_BOOTSTRAP_SERVER: broker:29092
    SCHEMA_REGISTRY_URL: http://datahub-gms:8080/schema-registry/api/

x-datahub-actions-service-dev: &datahub-actions-service-dev
  <<: *datahub-actions-service

services:
  datahub-actions-quickstart:
    <<: *datahub-actions-service
    container_name: actions
    profiles:
      - quickstart
      - quickstart-backend
    depends_on:
      datahub-gms-quickstart:
        condition: service_healthy
  datahub-actions-quickstart-cassandra:
    <<: *datahub-actions-service
    container_name: actions
    profiles:
      - quickstart-cassandra
    depends_on:
      datahub-gms-quickstart-cassandra:
        condition: service_healthy
  datahub-actions-quickstart-postgres:
    <<: *datahub-actions-service
    container_name: actions
    profiles:
      - quickstart-postgres
    depends_on:
      datahub-gms-quickstart-postgres:
        condition: service_healthy
  datahub-actions-quickstart-consumers:
    <<: *datahub-actions-service
    container_name: actions
    profiles:
      - quickstart-consumers
    depends_on:
      datahub-gms-quickstart-consumers:
        condition: service_healthy
  datahub-actions-debug:
    <<: *datahub-actions-service-dev
    container_name: actions-dev
    profiles:
      - debug
      - debug-backend
    depends_on:
      datahub-gms-debug:
        condition: service_healthy
  datahub-actions-debug-postgres:
    <<: *datahub-actions-service-dev
    container_name: actions-dev
    profiles:
      - debug-postgres
    depends_on:
      datahub-gms-debug-postgres:
        condition: service_healthy
  datahub-actions-debug-cassandra:
    <<: *datahub-actions-service-dev
    container_name: actions-dev
    profiles:
      - debug-cassandra
    depends_on:
      datahub-gms-debug-cassandra:
        condition: service_healthy
  datahub-actions-debug-consumers:
    <<: *datahub-actions-service-dev
    container_name: actions-dev
    profiles:
      - debug-consumers
    depends_on:
      datahub-gms-debug-consumers:
        condition: service_healthy
  datahub-actions-debug-neo4j:
    <<: *datahub-actions-service-dev
    container_name: actions-dev
    profiles:
      - debug-neo4j
    depends_on:
      datahub-gms-debug-neo4j:
        condition: service_healthy
  datahub-actions-debug-elasticsearch:
    <<: *datahub-actions-service-dev
    container_name: actions-dev
    profiles:
      - debug-elasticsearch
    depends_on:
      datahub-gms-debug-elasticsearch:
        condition: service_healthy