---
version: '3.5'
services:
  datahub-mce-consumer:
    image: keremsahin/datahub-mce-consumer:latest
    hostname: datahub-mce-consumer
    container_name: datahub-mce-consumer
    environment:
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
      - GMS_HOST=datahub-gms
      - GMS_PORT=8080

networks:
  default:
    name: datahub_network