---
version: '3.5'
services:
  datahub-mce-consumer:
    image: linkedin/datahub-mce-consumer:${DATAHUB_VERSION:-latest}
    build:
      context: ../../
      dockerfile: docker/mce-consumer/Dockerfile
    hostname: datahub-mce-consumer
    container_name: datahub-mce-consumer
    ports:
        - "9090:9090"
    environment:
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
      - GMS_HOST=datahub-gms
      - GMS_PORT=8080
      - KAFKA_MCE_TOPIC_NAME=MetadataChangeEvent
      - KAFKA_FMCE_TOPIC_NAME=FailedMetadataChangeEvent

networks:
  default:
    name: datahub_network
