apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datahub-mae-consumer.fullname" . }}
  labels:
    {{- include "datahub-mae-consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "datahub-mae-consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "datahub-mae-consumer.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.global.hostAliases }}
      hostAliases:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "datahub-mae-consumer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: datahub-gms-deployment-configmap
                  key: kafka.bootstrap.server
            - name: KAFKA_SCHEMAREGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: datahub-gms-deployment-configmap
                  key: kafka.schemaregistry.url
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: datahub-gms-deployment-configmap
                  key: elasticsearch.host
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: datahub-gms-deployment-configmap
                  key: elasticsearch.port
            - name: NEO4J_HOST
              valueFrom:
                configMapKeyRef:
                  name: datahub-gms-deployment-configmap
                  key: neo4j.host
            - name: NEO4J_URI
              valueFrom:
                configMapKeyRef:
                  name: datahub-gms-deployment-configmap
                  key: neo4j.uri
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: datahub-gms-deployment-secret
                  key: neo4j.username
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datahub-gms-deployment-secret
                  key: neo4j.password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
