# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

services:
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8090:8080
      - 7077:7077
  spark-worker-1:
    image: spark-slave
    container_name: spark-worker-1
    ports:
      - 8091:8081
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-slave
    container_name: spark-worker-2
    ports:
      - 8092:8081
    depends_on:
      - spark-master

networks:
  default:
    external: true
    name: datahub_network

