# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

# Override to use MariaDB as a backing store for datahub-gms.
---
services:
  mariadb:
    hostname: mariadb
    image: mariadb:10.5
    env_file: env/docker.env
    ports:
      - '3306:3306'

  datahub-gms:
    env_file: ../datahub-gms/env/dev.mariadb.env
    depends_on:
      - mariadb

networks:
  default:
    name: datahub_network
