apiVersion: v2
name: datahub
description: A Helm chart for LinkedIn DataHub
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: latest #0.3.1
dependencies:
  - name: datahub-gms
    version: 0.2.0
    repository: file://./charts/datahub-gms
    condition: datahub-gms.enabled
  - name: datahub-frontend
    version: 0.2.0
    repository: file://./charts/datahub-frontend
    condition: datahub-frontend.enabled
  - name: datahub-mae-consumer
    version: 0.2.0
    repository: file://./charts/datahub-mae-consumer
    condition: datahub-mae-consumer.enabled
  - name: datahub-mce-consumer
    version: 0.2.0
    repository: file://./charts/datahub-mce-consumer
    condition: datahub-mce-consumer.enabled