name: Check Datahub Jars

on:
  push:
    branches:
      - master
    paths:
      - "metadata-integration"
  pull_request:
    branches:
      - "**"
    paths:
      - "metadata-integration"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_jars:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        command: ["datahub-client", "datahub-protobuf", "spark-lineage"]
    runs-on: ubuntu-latest
    steps:
      - uses: acryldata/sane-checkout-action@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: check ${{ matrix.command }} jar
        run: |
          ./gradlew :metadata-integration:java:${{ matrix.command }}:build --info
          ./gradlew :metadata-integration:java:${{ matrix.command }}:javadoc
