name: ingestion base
on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - ".github/workflows/docker-ingestion-base.yml"
      - "docker/datahub-ingestion-base/**"
      - "gradle*"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/docker-ingestion-base.yml"
      - "docker/datahub-ingestion-base/**"
      - "gradle*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-base:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and Push image
        uses: ./.github/actions/docker-custom-build-and-push
        with:
          images: |
            acryldata/datahub-ingestion-base
          tags: latest
          username: ${{ secrets.ACRYL_DOCKER_USERNAME }}
          password: ${{ secrets.ACRYL_DOCKER_PASSWORD }}
          publish: ${{ github.ref == 'refs/heads/master' }}
          context: .
          file: ./docker/datahub-ingestion-base/Dockerfile
          platforms: linux/amd64,linux/arm64
