name: datahub-airflow docker acryl
on:
  workflow_run:
    workflows: ["pypi-release metadata-ingestion"]
    types:
      - completed

jobs:
  setup:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      publish: ${{ steps.publish.outputs.publish }}
      python_release_version: ${{ steps.python_release_version.outputs.release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compute Tag
        id: tag
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          TAG=$(echo ${GITHUB_REF} | sed -e 's,refs/tags/,,g')
          echo "tag=$TAG"
          echo "::set-output name=tag::$TAG"
      - name: Check whether publishing enabled
        id: publish
        env:
          ENABLE_PUBLISH: ${{ secrets.ORG_DOCKER_PASSWORD }}
        run: |
          echo "Enable publish: ${{ env.ENABLE_PUBLISH != '' }}"
          echo "::set-output name=publish::${{ env.ENABLE_PUBLISH != '' }}"
      - name: Compute Python Release Version
        id: python_release_version
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          RELEASE_VERSION=$(echo ${GITHUB_REF} | sed -e 's,refs/tags/v,,g')
          echo "release_version=$RELEASE_VERSION"
          echo "::set-output name=release_version::$RELEASE_VERSION"
  push_to_registries:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            acryldata/datahub-airflow
          # add git short SHA as Docker tag
          tag-custom: ${{ needs.setup.outputs.tag }}
          tag-custom-only: true
      - name: Login to DockerHub
        if: ${{ needs.setup.outputs.publish == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.ORG_DOCKER_PASSWORD }}
      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/airflow/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: ${{ needs.setup.outputs.publish == 'true' }}
          build-args: |
            RELEASE_VERSION=${{ needs.setup.outputs.python_release_version }}
