name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install DataHub CLI
        run: |
          python -m pip install --upgrade pip
          ./gradlew :metadata-ingestion:install
      - name: Start DataHub
        run: |
          source metadata-ingestion/venv/bin/activate
          datahub docker quickstart
        env:
          DATAHUB_TELEMETRY_ENABLED: false
      - name: Install dependencies
        run: npm install -g yarn && yarn
        working-directory: smoke-test/tests/playwright
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: smoke-test/tests/playwright
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: smoke-test/tests/playwright
        env:
          ADMIN_USERNAME: datahub
          ADMIN_PASSWORD: datahub

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: ðŸŽ­ Playwright Tests
          path: smoke-test/tests/playwright/playwright-report/results.json
          reporter: playwright-json
          fail-on-error: true

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: smoke-test/tests/playwright/playwright-report/
          retention-days: 30
