# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

name: yaml format
on:
  push:
    branches:
      - main
    paths:
      - "**/*.{yml,yaml}"
  pull_request:
    branches:
      - "**"
    paths:
      - "**/*.{yml,yaml}"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  yaml_format_check:
    name: yaml_format_check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: acryldata/sane-checkout-action@v4
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: run prettier --check
        run: |-
          ./gradlew :datahub-web-react:githubActionsPrettierCheck
